### ISSUE TITLE
{AttributeError} 'Certificate' object has no attribute 'sha256_fingerprint'

### ISSUE THREAD

**Issue by gurol** [androguard/androguard#504]
`show_Certificate(cert, short=False)` in `apk.py` raises AttributeError.

`print("SHA512: {}".format(cert.sha256_fingerprint))` call should be in try-catch.

Besides, there is an inconsistency in the print (label vs. value): SHA512 vs. sha256_fingerprint.

### System Information

- Androguard Version: master (3.2.0)
- Python Version: 2.7
- Operating System: macOS

[Sample file](https://github.com/droidefense/test-apps/blob/master/615fe78f3a644cb63df8b7918fb8d503%20SMS_Replicator_Secret.apk) (md5: 615fe78f3a644cb63df8b7918fb8d503)

**Comment by reox** [comment]
you are right, this is a bug caused by #486 

But sha256_fingerprint should be accessible on the certificate.
Can you check what version of asn1crypto you are using?

**Comment by reox** [comment]
@gurol have you checked your asn1crypto version? I also changed the setup.py to download a version which should work.

**Comment by gurol** [comment]
Yes, it was 0.22.0. It is OK with 0.24.0 (the latest now).

**Comment by reox** [comment]
okay thanks for the confirmation!
